# Generated by Django 5.1.2 on 2025-01-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.IntegerField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer'), ('C', 'Check'), ('O', 'Other')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loan_approved', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbankaccount')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
