# Generated by Django 5.1.4 on 2025-01-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
